os:
  - Visual Studio 2015

configuration:
  - Debug

platform:
  - Win32

before_build:
  - appveyor DownloadFile https://github.com/vladimirgamalian/sdl2_msvc_builds/releases/download/SDL2-Binaries/sdl2.zip
  - 7z x sdl2.zip -oC:\Libraries > nul
  - git submodule init && git submodule update
  - cmake -G "Visual Studio 14 2015" -DCMAKE_PREFIX_PATH="C:\Libraries"

build_script:
  - msbuild "sdl2pp_msvc2015.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Debug /p:Platform=Win32
  - msbuild "sdl2pp_msvc2015.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release /p:Platform=Win32

after_build:
  - md include
  - md include\SDL2pp
  - md include\SDL2pp\external
  - copy extlibs\libSDL2pp\SDL2pp\*.hh include\SDL2pp
  - copy extlibs\libSDL2pp\SDL2pp\external\libcpp_optional.hh include\SDL2pp\external\libcpp_optional.hh
  - 7z a sdl2ppd.zip -i@"debug.txt"
  - 7z a sdl2pp.zip -i@"release.txt"

artifacts:
  - path: sdl2ppd.zip
    name: sdl2ppd
  - path: sdl2pp.zip
    name: sdl2pp	

deploy:
  provider: GitHub
  release: libSDL2pp-bin
  description: 'Precompiled libSDL2pp mvsc2015 binaries'
  auth_token:
    secure: FLLAgKct3M0RM2UAGxPMC3CazyD4SyNVh4X3gdB8T1PHYtTvXJOYqG4D+6R9iKop
  artifact: sdl2pp, sdl2ppd
  draft: false
  prerelease: false
  on:
    branch: master
