os:
  - Visual Studio 2015

configuration:
  - Debug
  - Release

platform:
  - Win32

before_build:
  # download and unzip precompiled SDL2 libraries
  - appveyor DownloadFile https://github.com/vladimirgamalian/sdl2_msvc_builds/releases/download/SDL2-Binaries/sdl2.zip
  - 7z x sdl2.zip -oC:\Libraries > nul
  # create VS solution
  - cd C:\projects\sdl2pp_msvc2015
  - git submodule init && git submodule update
  - cmake -G "Visual Studio 14 2015" -DCMAKE_PREFIX_PATH="C:\Libraries"

build:
  project: sdl2pp_msvc2015.sln
