os:
  - Visual Studio 2015

configuration:
  - Debug

platform:
  - Win32

before_build:
  - appveyor DownloadFile https://github.com/vladimirgamalian/sdl2_msvc_builds/releases/download/SDL2-Binaries/sdl2.zip
  - 7z x sdl2.zip -oC:\Libraries > nul
  - git submodule init && git submodule update
  - cmake -G "Visual Studio 14 2015" -DCMAKE_PREFIX_PATH="C:\Libraries"

build:
  project: sdl2pp_msvc2015.sln

after_build:
  - md include
  - md include\SDL2pp
  - copy extlibs\libSDL2pp\SDL2pp\*.* include\SDL2pp
  - 7z a sdl2ppd.zip -i@"debug.txt"

artifacts:
  - path: sdl2ppd.zip
    name: sdl2ppd
